# Generated by Django 5.2.7 on 2025-10-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия, инициалы')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('phase', models.CharField(choices=[('before', 'До занятия'), ('after', 'После занятия')], max_length=10, verbose_name='Фаза')),
                ('q1', models.IntegerField(default=0, verbose_name='1. Самочувствие хорошее / плохое')),
                ('q2', models.IntegerField(default=0, verbose_name='2. Сильный / слабый')),
                ('q3', models.IntegerField(default=0, verbose_name='3. Пассивный / активный')),
                ('q4', models.IntegerField(default=0, verbose_name='4. Малоподвижный / подвижный')),
                ('q5', models.IntegerField(default=0, verbose_name='5. Веселый / грустный')),
                ('q6', models.IntegerField(default=0, verbose_name='6. Хорошее настроение / плохое')),
                ('q7', models.IntegerField(default=0, verbose_name='7. Работоспособный / разбитый')),
                ('q8', models.IntegerField(default=0, verbose_name='8. Полный сил / обессиленный')),
                ('q9', models.IntegerField(default=0, verbose_name='9. Медлительный / быстрый')),
                ('q10', models.IntegerField(default=0, verbose_name='10. Бездеятельный / деятельный')),
                ('q11', models.IntegerField(default=0, verbose_name='11. Счастливый / несчастный')),
                ('q12', models.IntegerField(default=0, verbose_name='12. Жизнерадостный / мрачный')),
                ('q13', models.IntegerField(default=0, verbose_name='13. Напряженный / расслабленный')),
                ('q14', models.IntegerField(default=0, verbose_name='14. Здоровый / больной')),
                ('q15', models.IntegerField(default=0, verbose_name='15. Безучастный / увлеченный')),
                ('q16', models.IntegerField(default=0, verbose_name='16. Равнодушный / взволнованный')),
                ('q17', models.IntegerField(default=0, verbose_name='17. Восторженный / унылый')),
                ('q18', models.IntegerField(default=0, verbose_name='18. Радостный / печальный')),
                ('q19', models.IntegerField(default=0, verbose_name='19. Отдохнувший / усталый')),
                ('q20', models.IntegerField(default=0, verbose_name='20. Свежий / изнуренный')),
                ('q21', models.IntegerField(default=0, verbose_name='21. Сонливый / возбужденный')),
                ('q22', models.IntegerField(default=0, verbose_name='22. Желание отдохнуть / работать')),
                ('q23', models.IntegerField(default=0, verbose_name='23. Спокойный / озабоченный')),
                ('q24', models.IntegerField(default=0, verbose_name='24. Оптимистичный / пессимистичный')),
                ('q25', models.IntegerField(default=0, verbose_name='25. Выносливый / утомляемый')),
                ('q26', models.IntegerField(default=0, verbose_name='26. Бодрый / вялый')),
                ('q27', models.IntegerField(default=0, verbose_name='27. Соображать трудно / легко')),
                ('q28', models.IntegerField(default=0, verbose_name='28. Рассеянный / внимательный')),
                ('q29', models.IntegerField(default=0, verbose_name='29. Полный надежд / разочарованный')),
                ('q30', models.IntegerField(default=0, verbose_name='30. Довольный / недовольный')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='san_app.participant')),
            ],
        ),
    ]
